### ISSUE TITLE
Please share the whole FlyReader code

### ISSUE THREAD

**Issue by mediaexplorer74** [yinyue200/FlyReaderTranslation#16]
Hello Yue Yin,

Please share the whole FlyReader code if You can...

I ' m big fanboy of "dead" WInPhones which still continue to support arm uwp (sdk 15063 min.) apps... =)
I noticed that your assembled (packaged) FlyReader is only 16299-compatible. It's not good :) 
So, I wanna try to start your src code "downgrading"  for better W10M (Windows 10 Mobile) compatibility :)

Best wishes,
Andrey aka MediaExplorer
"The last of [W 10 M]agicans" ))

**Comment by yinyue200** [comment]
Thank you for your support, we will seriously consider your suggestion.

Fly Reader actually supports Windows 10 Mobile, you can try to download version 1.4.102. If you have problems getting this version, we can provide assistance.

**Comment by mediaexplorer74** [comment]
> Thank you for your support, we will seriously consider your suggestion.
> 
> Fly Reader actually supports Windows 10 Mobile, you can try to download version 1.4.102. If you have problems getting this version, we can provide assistance.

Thank you for quick answer.
Waw, I found&installed your best app simply via MS Store. Crazy! So, no appx / src code needed... Um, I found even text to voice autotranslation and Russian localization. I m glad to see that clean and simple design. You did hard work, really!
You/your team is/are real coders! 
I started following you

![IMG_20230829_062919.jpg](https://github.com/yinyue200/FlyReaderTranslation/assets/12032735/3e6c24bd-eb4a-4451-bf21-926c51962100)

![IMG_20230829_064126.jpg](https://github.com/yinyue200/FlyReaderTranslation/assets/12032735/911b4de6-2294-4dc1-9320-0b8a0ae7b7d5)

![IMG_20230829_064224.jpg](https://github.com/yinyue200/FlyReaderTranslation/assets/12032735/20036dc4-7859-4f7c-bdf6-e39c80817d78)
